apiVersion: v1
kind: Namespace
metadata:
  name: odoo-prod
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: odoo-config
  namespace: odoo-prod
data:
  odoo.conf: |
    [options]
    addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
    admin_passwd = admin
    db_host = db
    db_port = 5432
    db_user = odoo
    db_password = odoo
    list_db = True
    log_level = info
    http_port = 8069
    gevent_port = 8072
    server_wide_modules = base,web
    workers = 6
    csv_internal_sep = ,
    data_dir = /var/lib/odoo/sessions
    screenshots = /tmp/odoo_tests
---
# PostgreSQL Deployment (ephemeral, tuned resources, with initdb mount)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: odoo-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: postgres
          image: postgres:17.5
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "2Gi"
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
            - name: initdb
              mountPath: /docker-entrypoint-initdb.d   # <-- mount initdb scripts here
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres", "-d", "postgres"]
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 5
      volumes:
        - name: pgdata
          emptyDir: {}
        - name: initdb
          configMap:
            name: initdb-scripts
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: odoo-prod
spec:
  selector:
    app: db
  ports:
    - port: 5432
      targetPort: 5432
---
# Odoo Deployment (scaled replicas, tuned resources/probes)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo
  namespace: odoo-prod
spec:
  replicas: 10                   # reduced replicas for quota, each pod has 6 workers
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:17.5
          command: ['sh', '-c', 'until pg_isready -h db -U postgres; do echo waiting for db; sleep 2; done;']
      containers:
        - name: odoo
          image: legacyg/dbmsdocker:with-addons-v1
          ports:
            - containerPort: 8069
            - containerPort: 8072
          env:
            - name: HOST
              value: db
            - name: USER
              value: odoo
            - name: PASSWORD
              value: odoo
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "2Gi"
          volumeMounts:
            - name: config
              mountPath: /etc/odoo/odoo.conf
              subPath: odoo.conf
          readinessProbe:
            httpGet:
              path: /web/login
              port: 8069
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /web/login
              port: 8069
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 5
      volumes:
        - name: config
          configMap:
            name: odoo-config
---
apiVersion: v1
kind: Service
metadata:
  name: odoo-svc
  namespace: odoo-prod
spec:
  type: LoadBalancer
  selector:
    app: odoo
  ports:
    - name: http
      port: 8069
      targetPort: 8069
    - name: longpoll
      port: 8072
      targetPort: 8072
