apiVersion: batch/v1
kind: Job
metadata:
  name: db-init
spec:
  template:
    spec:
      containers:
      - name: db-init
        image: postgres:17.5
        command: ["/bin/bash", "-c"]
        args:
          - |
            set -e
            echo "Waiting for PostgreSQL..."
            until pg_isready -h "$DB_HOST" -U "$DB_USER" -d "$DB_NAME"; do
              sleep 2
            done
            echo "PostgreSQL is ready."

            echo "Ensuring database exists: $DB_NAME"
            PGPASSWORD="$DB_PASSWORD" psql -h "$DB_HOST" -U "$DB_USER" -tc "SELECT 1 FROM pg_database WHERE datname = '$DB_NAME'" | grep -q 1 || \
              PGPASSWORD="$DB_PASSWORD" psql -h "$DB_HOST" -U "$DB_USER" -c "CREATE DATABASE $DB_NAME"

            echo "Restoring dump from /init/it2025.dump ..."
            PGPASSWORD="$DB_PASSWORD" pg_restore -h "$DB_HOST" -U "$DB_USER" -d "$DB_NAME" /init/it2025.dump

            echo "Restore completed."
        env:
        - name: DB_HOST
          value: futminna-postgres.postgres.database.azure.com
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: odoo-db-secret
              key: POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: odoo-db-secret
              key: POSTGRES_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: odoo-db-secret
              key: POSTGRES_DB
        - name: PGSSLMODE
          value: require
        volumeMounts:
        - name: dump-volume
          mountPath: /init
      restartPolicy: Never
      volumes:
      - name: dump-volume
        persistentVolumeClaim:
          claimName: odoo-dump-pvc
  backoffLimit: 3
