apiVersion: v1
kind: PersistentVolume
metadata:
  name: odoo-dump-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  azureFile:
    secretName: azure-storage-secret
    shareName: odoo-dumps
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-dump-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
